version: '3.9'
services:
  backend:
    container_name: app_backend
    build: ./
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - PASSWORD_POSTGRES=123456
      - HOST=db
      - DATABASE=testeNGCash
      - DB_USERNAME=postgres
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    volumes:
      - ./:/app-backend
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5